package promptgenerator.core;

public enum PromptPart {
    WORD_DEFINITION,
    WORD_BACK_SIDE,
    WORD_USAGE,
    WORD_EXAMPLES,
    WORD_RELATED_WORDS,
    WORD_SYNONYMS_COMPARISON,
    WORD_CONFUSED_TERMS,
    CHARACTER_USAGE,
    CHARACTER_BACK_SIDE,
    CHARACTER_EXAMPLES,
    CHARACTER_RADICALS_ANALYSIS,
    CHARACTER_READINGS,
    CHARACTER_RELATED_CHARACTERS,
    CHARACTER_CONFUSED_TERMS
}